# Generated by Django 5.2.14 on 2026-05-15 16:23

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0005_product_flash_sale_ends_at_product_flash_sale_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.products.models.get_supabase_storage,
                upload_to="categories/",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.products.models.get_supabase_storage,
                upload_to="products/",
            ),
        ),
    ]
