# Generated by Django 5.2.14 on 2026-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Color variant this image represents",
                max_length=30,
                null=True,
            ),
        ),
    ]
