# Generated by Django 5.2.14 on 2026-06-09 11:19

import apps.products.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_productimage_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductColorVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "color_name",
                    models.CharField(
                        help_text="Display name: 'Cobalt Indigo', 'Lagoon', 'Peach'",
                        max_length=50,
                    ),
                ),
                (
                    "hex_primary",
                    models.CharField(
                        help_text="Primary color hex: #5B6EF5", max_length=7
                    ),
                ),
                (
                    "hex_light",
                    models.CharField(
                        blank=True,
                        help_text="Light shade for hover effects (optional)",
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "hex_dark",
                    models.CharField(
                        blank=True,
                        help_text="Dark shade for borders (optional)",
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image showing this specific color variant",
                        storage=apps.products.models.get_supabase_storage,
                        upload_to="products/colors/",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-generated public URL",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which colors appear (0 = first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_variants_new",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Color Variant",
                "verbose_name_plural": "Product Color Variants",
                "ordering": ["display_order", "color_name"],
            },
        ),
        migrations.CreateModel(
            name="ProductSizeVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "size_name",
                    models.CharField(
                        help_text="Size label: 'S', 'M', 'L', 'XL', '40', '41', etc.",
                        max_length=20,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Unique SKU for this exact variant",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Current stock level"
                    ),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Price adjustment for this size (can be negative)",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which sizes appear (0 = first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "color_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_variants",
                        to="products.productcolorvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Size Variant",
                "verbose_name_plural": "Product Size Variants",
                "ordering": ["display_order", "size_name"],
            },
        ),
        migrations.AddIndex(
            model_name="productcolorvariant",
            index=models.Index(
                fields=["product", "is_active"], name="color_prod_active_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productcolorvariant",
            unique_together={("product", "color_name")},
        ),
        migrations.AddIndex(
            model_name="productsizevariant",
            index=models.Index(fields=["sku"], name="size_sku_idx"),
        ),
        migrations.AddIndex(
            model_name="productsizevariant",
            index=models.Index(
                fields=["color_variant", "stock_quantity"], name="size_color_stock_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productsizevariant",
            unique_together={("color_variant", "size_name")},
        ),
    ]
