# Generated by Django 5.2.14 on 2026-06-09 19:27

import apps.products.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_productcolorvariant_productsizevariant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariantV2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "color_name",
                    models.CharField(
                        help_text="Display name: Red, Blue, Cobalt Indigo, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "hex_primary",
                    models.CharField(
                        help_text="Primary hex color: #FF0000", max_length=7
                    ),
                ),
                (
                    "hex_light",
                    models.CharField(
                        blank=True,
                        help_text="Light shade (optional, for hover effects)",
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "hex_dark",
                    models.CharField(
                        blank=True,
                        help_text="Dark shade (optional, for borders)",
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload image for this color variant",
                        storage=apps.products.models.get_supabase_storage,
                        upload_to="products/variants/",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-generated Supabase public URL",
                        max_length=500,
                    ),
                ),
                (
                    "size_name",
                    models.CharField(
                        help_text="Size: S, M, L, XL, 40, 41, etc.", max_length=20
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Unique SKU: SHIRT-RED-M", max_length=100, unique=True
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Available stock for this variant"
                    ),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Price adjustment for this size/color (+/- from base price)",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (0 = first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants_v2",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant (Unified)",
                "verbose_name_plural": "Product Variants (Unified)",
                "ordering": ["display_order", "color_name", "size_name"],
                "indexes": [
                    models.Index(
                        fields=["product", "color_name"], name="varv2_prod_color_idx"
                    ),
                    models.Index(fields=["sku"], name="varv2_sku_idx"),
                    models.Index(
                        fields=["product", "is_active", "stock_quantity"],
                        name="varv2_prod_active_stock_idx",
                    ),
                ],
                "unique_together": {("product", "color_name", "size_name")},
            },
        ),
    ]
