# Generated by Django 5.2.14 on 2026-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="idempotency_key",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Unique key to prevent duplicate orders (OTP verification flow)",
                null=True,
                unique=True,
            ),
        ),
    ]
