# Generated by Django 5.2.14 on 2026-06-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_useraddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="label",
            field=models.CharField(
                blank=True,
                default="Home",
                help_text='e.g. "Home", "Office"',
                max_length=50,
            ),
        ),
    ]
